### ISSUE TITLE
Building test app fails on Windows MSVC 16 2019

### ISSUE THREAD

**Issue by AlexOpanasevych** [firebase/quickstart-cpp#116]
* Which Firebase Sample: Remote Config
  * Firebase C++ SDK version: 11.0.3
  * Additional SDKs you are using: Nothing
  * Platform you are using the SDK on: Windows
  * Platform you are targeting: Desktop

The issue happens every time I build project using Cmake

When I try to build test application using prebuilt binaries from [here](https://dl.google.com/firebase/sdk/cpp/firebase_cpp_sdk_11.3.0.zip), there happen some weird compiler errors, listed here:
`firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_cleanup_notifier.obj) : error LNK2019: unresol
ved external symbol __std_find_trivial_8 referenced in function "void * * __cdecl __std_find_trivial<void *,unsigned __
int64>(void * *,void * *,unsigned __int64)" (??$__std_find_trivial@PEAX_K@@YAPEAPEAXPEAPEAX0_K@Z) [C:\Users\Sasha\Docum
ents\projects2021\github-garbage-folder\firebase-test-app\desktop_testapp.vcxproj]
firebase_app.lib(d3d7d08a438878e74aeb2cbaaedfc967_flatbuffers.dir_Debug_idl_parser.obj) : error LNK2001: unresolved ext
ernal symbol __std_find_trivial_8 [C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-test-app\deskto
p_testapp.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_locale.obj) : error LNK2019: unresolved extern
al symbol u_errorName referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::all
ocator<char> > __cdecl firebase::internal::GetTimezone(void)" (?GetTimezone@internal@firebase@@YA?AV?$basic_string@DU?$
char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-tes
t-app\desktop_testapp.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_locale.obj) : error LNK2019: unresolved extern
al symbol ucal_getTimeZoneIDForWindowsID referenced in function "class std::basic_string<char,struct std::char_traits<c
har>,class std::allocator<char> > __cdecl firebase::internal::GetTimezone(void)" (?GetTimezone@internal@firebase@@YA?AV
?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [C:\Users\Sasha\Documents\projects2021\github-garbage-
folder\firebase-test-app\desktop_testapp.vcxproj]
firebase_app.lib(d94e1bff3c0e8414a6679ea91c3e103e_firebase_app.dir_Debug_heartbeat_storage_desktop.obj) : error LNK2019
: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl __std_find_trivial<char
const ,unsigned char>(char const *,char const *,unsigned char)" (??$__std_find_trivial@$$CBDE@@YAPEBDPEBD0E@Z) [C:\User
s\Sasha\Documents\projects2021\github-garbage-folder\firebase-test-app\desktop_testapp.vcxproj]
C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-test-app\Debug\desktop_testapp.exe : fatal error L
NK1120: 4 unresolved externals [C:\Users\Sasha\Documents\projects2021\github-garbage-folder\firebase-test-app\desktop_t
estapp.vcxproj]`

#### Steps to reproduce:

`cmake .`
`cmake --build .`

**Comment by AlexOpanasevych** [comment]
Also I forgot to mention that I'm using MSVC 16 2019 compiler

**Comment by AlmostMatt** [comment]
The unresolved symbols appear to be normal c++ classes and not firebase-specific. 
```
unresolved external symbol __std_find_trivial_8 ...
unresolved external symbol u_errorName referenced in function "class std::basic_string ...
unresolved external symbol ucal_getTimeZoneIDForWindowsID ...
unresolved external symbol__std_find_trivial_1 referenced in function "class std::basic_string ...
```

I am not entirely sure what would cause those failures but I suspect it is some incompatibility with the C++ settings the firebase binary was built with and the C++ compiler settings that you are using. Can you try updating your MSVC compiler and see if that has any impact on the error messages that you see? Also ensure that you are targeting C++ 14 or newer.
