### ISSUE TITLE
Where did the Message come from?

### ISSUE THREAD

**Issue by isipisi281** [firebase/quickstart-cpp#12]
Is there a way to figure out where the message did come from?
Lets say the app is in the background and user clicks on the notification.
Or the app is not in the background (closed) and the user clicks on the notification.
Or the app is the forground (opend) and we get a notification. 

There is no way to figure out whre the message did come from.
Is there mybe a way to figure out if the message we are reciving in c++ is coming from 
background, forground or closed app status?

It would be grait if there would be a property  in the  message.notification data where 
we could check where the notification did come from.

Or am i missing something here?

Regrads Isy

**Comment by isipisi281** [comment]
/// A flag indicating whether this message was opened by tapping a
  /// notification in the OS system tray. If the message was received this way
  /// this flag is set to true.
  bool notification_opened;

My fault didnt saw that ....

**Comment by stewartmiles** [comment]
No problem, does that solve your issue?

**Comment by isipisi281** [comment]
Yes. Thx
