### ISSUE TITLE
transaction crash

### ISSUE THREAD

**Issue by feixuwu** [firebase/quickstart-cpp#16]
run the database sample, 
I add  one line code, inside the transaction function 

int childCount = (int)data->children_count();

then the sample crash:
JNI DETECTED ERROR IN APPLICATION: the return type of CallIntMethodV does not match long com.google.firebase.database.MutableData.getChildrenCount()

**Comment by jonsimantov** [comment]
Thanks for reporting this bug, it seems like a pretty clear error and we should have a fix for it soon. I'll update this issue when a fix is released.

**Comment by jonsimantov** [comment]
Version 4.2.0 of the Firebase C++ SDK has been released, which fixes this issue. You can view the release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#4.2.0) and download the release from https://firebase.google.com/docs/cpp/setup.
