### ISSUE TITLE
An internal error has occurred

### ISSUE THREAD

**Issue by danesh-d** [firebase/quickstart-cpp#33]
I have tried running auth example. The code is built successfully but when I execute "desktop_testapp" I get the following errors:

Starting Auth tests.
Firebase App initializing app __FIRAPP_DEFAULT (default 1).
Created the Firebase app 16d09c0.
Created the Auth 16d33a0 class for the Firebase app.
No user signed in at creation time.
AuthStateListener called 0 times on registration.
IdTokenListener called 0 times on registration.
AuthStateListener called 0 times on SignOut() when already signed-out.
IdTokenListener called 0 times on SignOut() when already signed-out.
  Calling Auth::SignInAnonymously()...
ERROR: Auth::SignInAnonymously() completed with error: 1, `An internal error has occurred.`
ERROR: AuthStateListener called 0 times on SignInAnonymously().
ERROR: IdTokenListener called 0 times on SignInAnonymously().
Current user (nil)
ERROR: AuthStateListener called 0 times on SignOut().
ERROR: IdTokenListener called 0 times on SignOut().
Current user (nil)
  Calling CreateUserWithEmailAndPassword() to create temp user...
ERROR: CreateUserWithEmailAndPassword() to create temp user completed with error: 1, `An internal error has occurred.`
ERROR: Could not register new user.
  Calling Auth::SignInAnonymously() for User...
ERROR: Auth::SignInAnonymously() for User completed with error: 1, `An internal error has occurred.`
  Calling Auth::CreateUserWithEmailAndPassword() new email for delete...
ERROR: Auth::CreateUserWithEmailAndPassword() new email for delete completed with error: 1, `An internal error has occurred.`
  Calling Auth::SignInAnonymously() at end...
ERROR: Auth::SignInAnonymously() at end completed with error: 1, `An internal error has occurred.`
Completed Auth tests.

I have set the correct path to Firebase C++ SDK and also the file "google-services.json" is copied in the "testapp" directory.

Regards,

Danesh Daroui

**Comment by stewartmiles** [comment]
@danesh-d which platform are you targeting working on?

If you're seeing this error it's coming from the Firebase Auth backend which suggests your `google-services.json` file is pointing at a Firebase project with those authentication methods disabled.  You can turn on auth methods in the Firebase console.
