### ISSUE TITLE
[Desktop]Test FCM does not receive data

### ISSUE THREAD

**Issue by xdien** [firebase/quickstart-cpp#35]
I have used "Compose notification" to check but didn't receive a notification from firebase and didn't have any other information.
Operating system: linux(gentoo)
Operating system version: gcc version 7.3.0,cmake version 3.13.2
C++ SDK: 5.4.4
I'm not sure if I'm wrong or missing something, looking forward to helping!

>Firebase App initializing app __FIRAPP_DEFAULT (default 1).
Initialized Firebase App.
Initialize the Messaging library
Try to initialize Firebase Messaging
Initialized Firebase Cloud Messaging.
Display permission prompt if necessary.
Finished checking for permission.
  ::firebase::messaging::Subscribe("TestTopic")...
::firebase::messaging::Subscribe("TestTopic") completed as expected
  ::firebase::messaging::Subscribe("!@#$%^&*()")...
ERROR: ::firebase::messaging::Subscribe("!@#$%^&*()") completed with error: 0, `Successfully completed as a stub.`

**Comment by alexames** [comment]
FCM isn't implemented on desktop, just on iOS and Android, so the functions are all stubbed out. This is so that you can built your app on all three platforms without changing the code. However, on desktop the functions won't do anything.

**Comment by xdien** [comment]
Thank you for providing more information. I am intending to write a code for all platforms with Qt. Hopefully firebase will soon be completed on the desktop.
