### ISSUE TITLE
OnMessage not fired when app is in background - IOS

### ISSUE THREAD

**Issue by tezine** [firebase/quickstart-cpp#37]
Hi, 
Firebase C++ is working great on Android, but I'm facing some issues with IOS. 
I'm sending a data message to one iOS Device like this:
```
{
	"to":"mykey",
	"data":{
		"title": "hello",
    	        "body": "this is body",		
		"key1":"value1",
		"key2":"value2",
		"message":"message X"
	},
	"priority":"high"
}
```
The message above fires the C++ <b>OnMessage</b> when the iOS app is in foreground, but it's not received when it's in background. 
Any ideas on how to make it work and also display a notification when a message is received in background? 

Here's my AppDelegate.m:
```
@interface QIOSApplicationDelegate
@end
//! Add a category to QIOSApplicationDelegate
@interface QIOSApplicationDelegate (QFacebookApplicationDelegate) //<UNUserNotificationCenterDelegate>
@end
NSString *const kGCMMessageIDKey = @"gcm.message_id";
@implementation QIOSApplicationDelegate (QFacebookApplicationDelegate)

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
	// Override point for customization after application launch.
	NSLog( @"Firebase configured.==============================================" );
    [FIRApp configure];
    
    // [START set_messaging_delegate]
    [FIRMessaging messaging].delegate = self;
    // [END set_messaging_delegate]
    
    // Register for remote notifications. This shows a permission dialog on first run, to
    // show the dialog at a more appropriate time move this registration accordingly.
    // [START register_for_notifications]
    if ([UNUserNotificationCenter class] != nil) {
        // iOS 10 or later
        // For iOS 10 display notification (sent via APNS)
        [UNUserNotificationCenter currentNotificationCenter].delegate = self;
        UNAuthorizationOptions authOptions = UNAuthorizationOptionAlert |
        UNAuthorizationOptionSound | UNAuthorizationOptionBadge;
        [[UNUserNotificationCenter currentNotificationCenter]
         requestAuthorizationWithOptions:authOptions
         completionHandler:^(BOOL granted, NSError * _Nullable error) {
             // ...
         }];
    } else {
        // iOS 10 notifications aren't available; fall back to iOS 8-9 notifications.
        UIUserNotificationType allNotificationTypes =
        (UIUserNotificationTypeSound | UIUserNotificationTypeAlert | UIUserNotificationTypeBadge);
        UIUserNotificationSettings *settings =
        [UIUserNotificationSettings settingsForTypes:allNotificationTypes categories:nil];
        [application registerUserNotificationSettings:settings];
    }
    
    [application registerForRemoteNotifications];
    // [END register_for_notifications]
	return YES;
}
@end
```
I'm using Firebase CPP 5.4.4
Thank you, 
  Bruno.

**Comment by jonsimantov** [comment]
You shouldn't need any of that notifications stuff in your app delegate if you are using the C++ SDK. The SDK uses swizzling to hook into those notifiers directly.

Could you see if you are able to reproduce the issue using the C++ quick start? (this GitHub project). And also if you remove all of the notifications-related code from your app delegate.

**Comment by chkuang-g** [comment]
@tezine Just to follow-up.  Are you able to resolve your issue?

**Comment by stewartmiles** [comment]
@tezine the message is not received in the background on iOS until the user taps on the message in the notification tray (see https://firebase.google.com/docs/cloud-messaging/ios/receive#handle_messages_received_through_the_apns_interface ).  iOS doesn't really let you run your whole application in the background for a long time like Android.  We're likely to add support for iOS extensions for Cloud Messaging to allow you to take action when a message is received like customization of the notification or caching, but that's all we can do I'm afraid.

As @jonsimantov and @chkuang-g mentioned, you don't need any custom AppDelegate code in the C++ SDK, we hook everything for you.  If you follow the sample code (in this repo) you'll see what you need.
