### ISSUE TITLE
[Admob] IOS : Error while loading a rewarded video ad

### ISSUE THREAD

**Issue by doandoindi** [firebase/quickstart-cpp#39]
Hello team,

I'm trying to using the Admob tutorial. Unfortunately I always get the error while loading the rewarded video ads.

The log I got like:
```
2019-12-05 11:13:07.176988+0700 testapp[462:43948] Initializing rewarded video.
2019-12-05 11:13:08.177713+0700 testapp[462:43948] Setting rewarded video listener.
2019-12-05 11:13:08.177999+0700 testapp[462:43948] Loading a rewarded video ad.
2019-12-05 11:13:27.262124+0700 testapp[462:43948] ERROR: Action failed with error code 4 and message "An internal SDK error occurred.".
2019-12-05 11:13:27.262865+0700 testapp[462:43948] Done!
2019-12-05 11:16:46.051925+0700 testapp[462:44341] [BoringSSL] nw_protocol_boringssl_get_output_frames(1301) [C3.1:2][0x1060379d0] get output frames failed, state 8196
```
I'm using: 
- firebase_cpp_sdk_6.7.0, universal IOS framework
- Pod : 'Firebase/Analytics', '6.12.0' ;  'Firebase/AdMob', '6.12.0'
- Our AdMobAppID 
- RewardedVideoAdUnit test : "ca-app-pub-3940256099942544/6386090517"

You can find for the full console log in here : [IOS_Error_RewardedVideo_log.txt](https://github.com/firebase/quickstart-cpp/files/3925128/IOS_Error_RewardedVideo_log.txt)

Could you help me to take a look and show me how to overcome this error?

**Comment by chkuang-g** [comment]
Hi @doandoindi 

I think Firebase C++ 6.7.0 is pointing to Pod version 6.10.0.  And 6.12.0 is for the C++ SDK 6.8.0, which we just release!

Could you change the Pod version to 6.10.0 and try again?  Ex. Pod : 'Firebase/Analytics', '6.10.0' ; 'Firebase/AdMob', '6.10.0'
https://github.com/firebase/quickstart-cpp/blob/master/admob/testapp/Podfile#L5

Shawn

**Comment by doandoindi** [comment]
Hi @chkuang-g 

It's working with the Pod version 6.10.0 as your suggestion. I'm thinking if some people will be seen the same problem while trying to have Firebase C++ SDK on their application.

Do we have somewhere to show which Pod version should be used with which Firebase C++ version? It's a very helpful IMO.

Thank you Shawn,
D.

**Comment by chkuang-g** [comment]
You should be able to find this information in readme.md under your Firebase C++ SDK folder.  See "Frameworks" section.

Ex. For our 6.8.0 relaese, you should see 
```
| Firebase AdMob               | firebase_admob.framework                     |
|                              | firebase.framework                           |
|                              | Firebase/AdMob Cocoapod (6.12.0)             |

```
