### ISSUE TITLE
[Desktop] [Database] [ARM - Raspberry Pi] Compile problem

### ISSUE THREAD

**Issue by Trootyl** [firebase/quickstart-cpp#42]
### Please fill in the following fields:
Firebase C++ SDK version: 6.9.0
Firebase plugins in use: App, Auth, Database
Platform you are using the SDK on (Mac, Windows, or Linux): Raspberry Pi 4 - Raspbian
Platform you are targeting (iOS, Android, and/or desktop): desktop

I have problem with compilation database_testapp on Raspberry Pi 4. CPU it's not x86/64, but ARM and when I use command: "cmake --build ." I have problem like this:

[100%] Linking CXX executable desktop_testapp
/usr/bin/ld: /home/pi/e-signboard/firebase_cpp_sdk/libs/linux/x86_64/libfirebase_database.a: error adding symbols: file format not recognized
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/desktop_testapp.dir/build.make:102: desktop_testapp] Error 1
make[1]: *** [CMakeFiles/Makefile2:73: CMakeFiles/desktop_testapp.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

On Intel i5-6300HQ and Ubuntu 18.04 LTS everything is fine. I tryied use all libs, but all didn't work.

Is a chance to compile this program on Raspberry with C++ code? I need Firebase Database to use with Raspberry. I know there are Helper Library like pyrebase, etc., but code is in Python.

**Comment by jonsimantov** [comment]
The Linux binary desktop version of the Firebase C++ SDK is indeed only compiled for x86/x64, not for ARM (which is required for Raspberry Pi).

I would recommend taking a look at the [open-source version of the Firebase C++ SDK](https://github.com/firebase/firebase-cpp-sdk/), which you can try compiling on your Raspberry Pi.

Note that we have not done this ourselves but (on a personal note) I'm very interested to see if it works. :grin:
