### ISSUE TITLE
C++ driver support 

### ISSUE THREAD

**Issue by Natarajan77** [firebase/quickstart-cpp#45]
Can you please tell me for firestore do you have driver support for c++ ?

or if we have to use c++ it has to go thru from firebase SDK?

**Comment by Natarajan77** [comment]
For example if you take mongodb it has driver available for c++...like that does firestore has driver available to program with C++...we are developing in house application and planning to use firestore as nosql db....

Thanks for your time.

**Comment by morganchen12** [comment]
Closing this in favor of https://github.com/firebase/firebase-ios-sdk/issues/5673.
