### ISSUE TITLE
incompatibility with android sdk and cpp sdk

### ISSUE THREAD

**Issue by dudochkin-victor** [firebase/quickstart-cpp#7]
There some incompatibility:
- firebasee android sdk - 10.2.4
- firebase cpp sdk - 3.1.1
So Firebase send invite but cant decode project id anr return Error 500.

05-12 04:21:18.676 16100-16156/ru.gogoo.sushi D/cocos2d-x debug info: Initializing Firebase for Android.
05-12 04:21:18.706 16100-16100/ru.gogoo.sushi D/Cocos2dxActivity: onWindowFocusChanged() hasFocus=true
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/FirebaseOptions$Builder;.setProjectId(Ljava/lang/String;)Lcom/google/firebase/FirebaseOptions$Builder;"
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.nativeInit(Native Method)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.onSurfaceCreated(Cocos2dxRenderer.java:72)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err: java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/FirebaseOptions;.getProjectId()Ljava/lang/String;"
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.nativeInit(Native Method)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at org.cocos2dx.lib.Cocos2dxRenderer.onSurfaceCreated(Cocos2dxRenderer.java:72)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1500)
05-12 04:21:18.736 16100-16156/ru.gogoo.sushi W/System.err:     at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
05-12 04:21:18.766 16100-16115/ru.gogoo.sushi W/art: Suspending all threads took: 21.118ms
05-12 04:21:18.776 16100-16144/ru.gogoo.sushi D/FA: Connected to remote service

**Comment by stewartmiles** [comment]
Looks like you're missing the Java components for Android, see our
Cocos2d-x sample projects (https://github.com/firebase/cocos2dx-cpp-sample)
and setup page (https://firebase.google.com/docs/cpp/setup#dependencies_1) for
the requirements.

**Comment by dudochkin-victor** [comment]
my steps to setup project:
Java part
1. i get sha1 hash from my debug and release keystore and put them both
into firebase console
2. download google-services.json from firebase console and place it into
app subfolder in proj.android-studio
3. added

classpath 'com.google.gms:google-services:3.0.0'

into top project build.gradle

4. added

compile ('com.google.firebase:firebase-invites:10.2.4')
compile ('com.google.android.gms:play-services-base:10.2.4')

into app build.gradle (into dependencies section)

5. added

apply plugin: 'com.google.gms.google-services'

into bottom of app build.gradle

6. and syncing project in android studio with succesful. so i can say that
the java dependencies installed successful


C++ part

7. download c++ sdk firebase_cpp_sdk_3.1.1.zip extracted it
8. added

systemProp.firebase_cpp_sdk.dir=/home/Workspaces/firebase_cpp_sdk

into gradle.properties (however it is not worked)

9. added

FIREBASE_CPP_SDK_DIR:=/home/Workspaces/firebase_cpp_sdk

# With Firebase libraries for the selected build configuration (ABI + STL)
STL:=$(firstword $(subst _, ,$(APP_STL)))
FIREBASE_LIBRARY_PATH:=\
$(FIREBASE_CPP_SDK_DIR)/libs/android/$(TARGET_ARCH_ABI)/$(STL)

include $(CLEAR_VARS)
LOCAL_MODULE:=firebase_app
LOCAL_SRC_FILES:=$(FIREBASE_LIBRARY_PATH)/libapp.a
LOCAL_EXPORT_C_INCLUDES:=$(FIREBASE_CPP_SDK_DIR)/include
include $(PREBUILT_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:=firebase_invites
LOCAL_SRC_FILES:=$(FIREBASE_LIBRARY_PATH)/libinvites.a
LOCAL_EXPORT_C_INCLUDES:=$(FIREBASE_CPP_SDK_DIR)/include
include $(PREBUILT_STATIC_LIBRARY)

into top of Android.mk

10. changed some lines in Android.mk

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../../Classes \
   $(FIREBASE_CPP_SDK_DIR)/include

to correct handling includes in Android Studio

LOCAL_STATIC_LIBRARIES := cocos2dx_static \
   firebase_invites \
   firebase_app

to link static libs described above

11. At that moment i was syncing again and build app without errors.

12. changed Appdelegate.cpp

firebase::App::Create(firebase::AppOptions(), JniHelper::getEnv(),
                    JniHelper::getActivity());

there error in Firebase documentation (AppOption is not allow "Application
Name" now).

13. after started application i has errors.
14. after that i open com.google.firebase.FirebaseOptions file in Android
Studion and there no setProjectId and getProjectId methods.

15. i added handler to send invite and invite sended succesful l to my
email (Firebase is cant handle it on website, but succesfull handled from
my Android device)

PS. I have additional question about invitation: Can i send invitation from
one my Android application to my other Application?




2017-05-12 4:55 GMT+07:00 Stewart Miles <notifications@github.com>:

**Comment by stewartmiles** [comment]
Ah I missed that this is a warning.

05-12 04:21:18.736 16100-16156/ru.gogoo.sushi *W*/System.err:
java.lang.NoSuchMethodError: no non-static method "Lcom/google/firebase/
FirebaseOptions$Builder;.setProjectId(Ljava/lang/
String;)Lcom/google/firebase/FirebaseOptions$Builder;"

The app should still be created successfully.  We're anticipating new API
changes in the Android SDK which hasn't been released yet, that's all.
