### ISSUE TITLE
Project is some update needs. (gradle.properties, AndroidMnifest.xml, google-services.json)

### ISSUE THREAD

**Issue by masteage** [firebase/quickstart-cpp#82]
### Please fill in the following fields:
* macOS Catalina : 10.15.6
* Android Studio : v4.0.1
* Firebase C++ SDK version : v6.15.1
* Firebase plugins in use : admob
* Platform you are targeting Android (Simulator)

### Please describe the issue here:

* *gradle.properties*
   * add file "gradle.properties"
   * add Adndroid X setging
   * add firebase c++ sdk setting
   * https://github.com/firebase/quickstart-cpp/commit/742e95d0de47cefa5c4c1cc08d6f54df09edd0c7

* *AndroidMnifest.xml*
   * add sample admob app id 
   * https://github.com/firebase/quickstart-cpp/commit/6b4f5835ad3305553934b6e4a6c22975a7efbde5

* *google-services.json*
   * add mock google-services.json
   * https://github.com/firebase/quickstart-cpp/commit/e225bcbdcb276fc1ecaf529adf5cace5715e0a7e
   * from : https://github.com/firebase/quickstart-android/blob/master/mock-google-services.json

### Please answer the following, if applicable:

* Have you been able to reproduce this issue with just the Firebase C++ quickstarts (this GitHub project)?
   * -> YES

* What's the issue repro rate? (eg 100%, 1/5 etc)
   * -> 100%

**Comment by chkuang-g** [comment]
Hi @masteage 

Thank you for the suggestions.

I think the AndroidX/Jetifier change in gradle.properties make sense.  However, all of the others are documented in [readme](https://github.com/firebase/quickstart-cpp/tree/master/admob/testapp#android).

I think you still need to follow instructions from readme for the sample Admob App Id and mock google-services.json anyway.  Is there a particular reason you think those change are necessary?

Shawn
