### ISSUE TITLE
Firebase C++ SDK

### ISSUE THREAD

**Issue by Enterprises-Gracida-Veracruz** [firebase/quickstart-cpp#85]
https://developers.google.com/appmaker
[Firebase 70 org.chromium.webapk.a1a24df2461346d0a.apk]
https://cloud.google.com/sdk/cloud-client-libraries?authuser=0

**Comment by Enterprises-Gracida-Veracruz** [comment]
https://developers.google.com/appmaker/support.google.com/a

**Comment by morganchen12** [comment]
There doesn't appear to be anything actionable in this issue.
