### ISSUE TITLE
build/build.CMAKE

### ISSUE THREAD

**Issue by Enterprises-Gracida-Veracruz** [firebase/quickstart-cpp#88]
gtm.js <head> <shared_project_sdk> <body>  
<build.react-native.dev/docs/pixelratio> <https://workspace.google.com/intl/es/terms/use_policy.html> https://plus.google.com/up?pli=1/google.dev/u/new/g.page/enterprise-gracida-veracruz.negocio.site/

**Comment by morganchen12** [comment]
There doesn't appear to be anything actionable in this issue.
