### ISSUE TITLE
iOs FIRMessaging didReceiveMessage not implemented

### ISSUE THREAD

**Issue by isipisi281** [firebase/quickstart-cpp#9]
Hello together, i implemented messaging on iOs but when i send a message in the firebase console
and the device gets the message it gives me this output:

2017-07-17 12:42:24.803 App[1608] <Warning> [Firebase/Messaging][I-FCM002019] FIRMessaging received data-message, but FIRMessagingDelegate's-messaging:didReceiveMessage: not implemented

Is it possible that there is a missing function in the c++/ios part?

**Comment by alexames** [comment]
Thanks for the report. It looks like there was indeed an oversight. I'm working on a fix and I'll leave a comment here when it's available.

**Comment by jonsimantov** [comment]
Version 4.0.3 of the Firebase C++ SDK has been released, which fixes this issue. You can view the release notes [here](https://firebase.google.com/support/release-notes/cpp-relnotes#4.0.3) and download the release from https://firebase.google.com/docs/cpp/setup.

**Comment by saqibomer** [comment]
Use Dispatch que
`DispatchQueue.main.async(execute: {
                        UIApplication.shared.registerForRemoteNotifications()
                    })`

**Comment by stewartmiles** [comment]
@saqibomer are you saying you still have issues?

**Comment by saqibomer** [comment]
My bad. I had not added `FirebaseAppDelegateProxyEnabled` and was having that issue. Deleted comment. @stewartmiles
